version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # puerto del broker
      - "15672:15672" # interfaz web
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

  sender-fullcontainers:
    build:
      context: ./producers/sender-fullcontainers
    container_name: sender
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    command: ["java", "-cp", "target/classes:target/dependency/*", "com.example.SenderFullContainers"]

  consumer-route-optimizer:
    build:
      context: ./consumers/consumer-route-optimizer
    container_name: consumer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
